package com.opensource.techblog.springmvc.portlet1.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Product service. Represents a row in the &quot;legalwiz_Product&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.opensource.techblog.springmvc.portlet1.model.impl.ProductModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.opensource.techblog.springmvc.portlet1.model.impl.ProductImpl}.
 * </p>
 *
 * @author LegalWiz
 * @see Product
 * @see com.opensource.techblog.springmvc.portlet1.model.impl.ProductImpl
 * @see com.opensource.techblog.springmvc.portlet1.model.impl.ProductModelImpl
 * @generated
 */
public interface ProductModel extends BaseModel<Product> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a product model instance should use the {@link Product} interface instead.
     */

    /**
     * Returns the primary key of this product.
     *
     * @return the primary key of this product
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this product.
     *
     * @param primaryKey the primary key of this product
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the product ID of this product.
     *
     * @return the product ID of this product
     */
    public long getProductId();

    /**
     * Sets the product ID of this product.
     *
     * @param productId the product ID of this product
     */
    public void setProductId(long productId);

    /**
     * Returns the group ID of this product.
     *
     * @return the group ID of this product
     */
    public long getGroupId();

    /**
     * Sets the group ID of this product.
     *
     * @param groupId the group ID of this product
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this product.
     *
     * @return the company ID of this product
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this product.
     *
     * @param companyId the company ID of this product
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this product.
     *
     * @return the user ID of this product
     */
    public long getUserId();

    /**
     * Sets the user ID of this product.
     *
     * @param userId the user ID of this product
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this product.
     *
     * @return the user uuid of this product
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this product.
     *
     * @param userUuid the user uuid of this product
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the product name of this product.
     *
     * @return the product name of this product
     */
    @AutoEscape
    public String getProductName();

    /**
     * Sets the product name of this product.
     *
     * @param productName the product name of this product
     */
    public void setProductName(String productName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Product product);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Product> toCacheModel();

    @Override
    public Product toEscapedModel();

    @Override
    public Product toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
